---
all:
  hosts:
    nginx:
      ansible_host: 172.20.1.15

  children:
    nginx_group:
      hosts:
        nginx:

    prometheus:
      hosts:
        prom-sauron:
          ansible_host: 172.20.1.220
...