---
all:
  hosts:
    nginx:
      ansible_host: 172.20.1.10
    ticket1:
      ansible_host: 172.20.1.15
    ticket2:
      ansible_host: 172.20.1.16
    ticket3:
      ansible_host: 172.20.1.17
    prom-sauron:
      ansible_host: 172.20.1.220

  children:
    nginx_group:
      hosts:
        nginx:

    backend:
      hosts:
        ticket1:
        ticket2:
        ticket3:

    prometheus:
      hosts:
        prom-sauron:
...