{
 "title": "Mongodb_replica_sets",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "replicaSets", "query": "label_values(mongodb_role)" },
   {
    "name": "replicaSet_host",
    "query": "label_values(mongodb_connections{env=\"Otus\",exporter=\"mongodb_exporter\",mongodb_role=\"$replicaSets\"},instance)"
   },
   {
    "name": "ReplicaSet_master",
    "query": "label_values(mongodb_mongod_replset_member_state{mongodb_role=\"$replicaSets\",state=\"PRIMARY\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "MongoDB not available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mongodb_up{env=\"Otus\",exporter=\"mongodb_exporter\",instance=~\"$replicaSet_host\",mongodb_role=~\"$replicaSets\"}) by (dlog_hostname)",
     "legendFormat": "{{dlog_hostname}}"
    }
   ]
  },
  {
   "title": "ReplicaSet state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mongodb_mongod_replset_member_state{mongodb_role=~\"$replicaSets\",instance=~\"$replicaSet_host\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ReplicaLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(avg(mongodb_mongod_replset_member_replication_lag{env=\"Otus\",exporter=\"mongodb_exporter\",instance=~\"$replicaSet_host\",mongodb_role=~\"$replicaSets\"}) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OplogSize,s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mongodb_mongod_replset_oplog_head_timestamp{instance=~\"$replicaSet_host\"}-mongodb_mongod_replset_oplog_tail_timestamp{instance=~\"$replicaSet_host\"}) by (dlog_hostname)",
     "legendFormat": "{{dlog_hostname}}"
    }
   ]
  },
  {
   "title": "Connections count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mongodb_mongod_wiredtiger_log_operations_total{env=\"Otus\",exporter=\"mongodb_exporter\",instance=~\"$replicaSet_host\",mongodb_role=~\"$replicaSets\",type=\"scan\"}) by (dlog_hostname)",
     "legendFormat": "{{dlog_hostname}}"
    }
   ]
  },
  {
   "title": "Operations, count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(mongodb_op_counters_total{env=\"Otus\",exporter=\"mongodb_exporter\",instance=~\"$replicaSet_host\",mongodb_role=~\"$replicaSets\"}[1m])) by (name,type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connections count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mongodb_connections{env=\"Otus\",exporter=\"mongodb_exporter\",instance=~\"$replicaSet_host\",state=\"current\"}) by (dlog_hostname)",
     "legendFormat": "{{dlog_hostname}}"
    }
   ]
  }
 ]
}