---
# defaults file for node-exporter
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_version: 1.0.0-rc.0
node_exporter_work_dir: /opt/node_exporter
# node_exporter_