---
# tasks file for nginx
- name: NGINX | Allow port {{ nginx_port }} in firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - "{{ nginx_port }}"

- name: NGINX | restart_firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: restarted

- name: NGINX | Install nginx Repo
  block:
  - name: Install Repo ELEL-Release
    yum:
      name: epel-release
      state: present
    tags:
      - epel-package
      - packages

  - name: NGINX | Install packages
    yum:
      name: "{{ item }}"
      state: latest
    loop:
    - "{{ nginx_pakages }}"
    notify:
      - restart nginx
    tags:
      - nginx-package
      - packages

  - name: NGINX | Create NGINX config file from template
    template:
      src: "{{ group_names[0] }}.conf.j2"
      dest: /etc/nginx/nginx.conf
      mode: 0644
      owner: root
      group: root
    notify:
      - reload nginx
    tags:
      - nginx-configuration




  - name: NGINX | Add upstreams list to nginx config
    blockinfile:
      path: /etc/nginx/nginx.conf
      block: |2
                server {{ item }}:{{ nginx_backend_port }} max_fails=3;
      marker: "        # {mark} ANSIBLE MANAGED - adding servers backend {{ item }}"
      insertafter: "hash *"
    loop:  "{{ nginx_backend_ip }}"
    when: (inventory_hostname in groups.nginx_group)

  - name: NGINX| start service
    systemd:
      name: nginx
      state: started
      enabled: yes

  - name: NGINX| restart service
    systemd:
      name: nginx
      state: restarted
      enabled: yes

  when: ansible_facts['distribution'] == 'CentOS'
