---
- name: nginx
  hosts:
    - nginx_group
    - backend
  become: true
  become_method: sudo
  gather_facts: yes
  roles:
    - nginx

- name: Backend
  hosts: backend
  become: true
  become_method: sudo
  gather_facts: yes
  roles:
    - ticket

- name: Node-exporter
  hosts:
    - nginx_group
    - backend
  become: true
  become_method: sudo
  gather_facts: yes
  roles:
    - node-exporter
    - node-exporter-nginx

- name: install prometheus
  hosts: prometheus
  become: true
  gather_facts: yes
  roles:
    - prometheus
    - grafana
    - node-exporter
